<?php
namespace \App\Roles\UserClass;
use App\Roles\User;
class UserClass extends User\User {

function getPersonal($username, $id): string
{
    return parent::getPersonal($username, $id); // TODO: Change the autogenerated stub
}
function getMail($email, $username, $id, $password)
{
    parent::getMail($email, $username, $id, $password); // TODO: Change the autogenerated stub
}
public  function getUsername(): string
{
    return User::with('roles')->findOrFail(Auth::id());
}

}